from typing import Any, Dict, Iterator, Sequence

class ParameterGrid:
    def __init__(self, param_grid: Dict[str, Sequence[Any]]) -> None: ...
    def __iter__(self) -> Iterator[Dict[str, Any]]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, ind: int) -> Dict[str, Any]: ...
